apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: USERNAME/healthcare-app:1.0
        ports:
        - containerPort: 8080
