apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: LoadBalancer
  selector:
    app: healthcare
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
